[colors]
; Nord color palette
polar-night-0 = #2e3440
polar-night-1 = #3b4252
polar-night-2 = #434c5e
polar-night-3 = #4c566a
snow-storm-0  = #d8dee9
snow-storm-1  = #e5e9f0
snow-storm-2  = #eceff4
frost-0       = #8fbcbb
frost-1       = #88c0d0
frost-2       = #81a1c1
frost-3       = #5e81ac
aurora-red    = #bf616a
aurora-orange = #d08770
aurora-yellow = #ebcb8b
aurora-green  = #a3be8c
aurora-purple = #b48ead

[colors]
background     = ${colors.polar-night-0}
background-alt = ${colors.frost-2}
foreground     = ${colors.snow-storm-0}
primary        = ${colors.frost-1}
secondary      = ${colors.polar-night-1}
alert          = ${colors.aurora-red}
disabled       = ${colors.polar-night-3}

[bar/toph]
monitor = ${env:MONITOR:}
width = 100%
height = 18pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

bottom = false
top = true
line-size = 6pt

border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

font-0 = JetBrains Mono:size=8;2

modules-left = xworkspaces xwindow
modules-right = pulseaudio battery memory cpu brightness date systray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.frost-2}
label-active-foreground = ${colors.polar-night-0}
label-active-underline= ${colors.frost-1}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#ebcb8b}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/battery]
type = internal/battery
format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}
full-at = 99
format-charging = <animation-charging> <label-charging>
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-charging-foreground = ${colors.aurora-orange}
format-discharging = <ramp-capacity> <label-discharging>
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
low-at = 5
battery = BAT1
adapter = ACAD
poll-interval = 5

[module/brightness]
type = custom/script
exec = $HOME/.config/polybar/brightness.sh
interval = 1
format-prefix = "EYE "
format-prefix-foreground = ${colors.frost-3}
scroll-up = $HOME/.config/polybar/brightness.sh up
scroll-down = $HOME/.config/polybar/brightness.sh down
label = %output%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#ebcb8b}%ifname%%{F#4c566a} connected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#ebcb8b}%ifname%%{F-} %essid%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#ebcb8b}%ifname%%{F-} connected

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d %r
date-alt = %Y-%m-%d %r
label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini

